### ISSUE TITLE
Missing url in Disconnect/Closed events

### ISSUE THREAD

**Issue by T-Erpstra** [nats-io/nats.net.v1#111]
I have this code for the connection callbacks:

```
Options opts = ConnectionFactory.GetDefaultOptions();
opts.ClosedEventHandler += ( s, e ) => {
    _logger.Error( "Connection to {0} was closed.", e.Conn.ConnectedUrl );
};
opts.DisconnectedEventHandler += ( s, e ) => {
    _logger.Error( "Disconnected from {0}.", e.Conn.ConnectedUrl );
};
```

It seems that the e.Conn.ConnectedUrl is null on both events, which makes it hard to know from which server one lost the connection.

Also, I miss a "ConnectedEventHandler" so that I can know when the first connection actually succeeded and to which server (ReconnectedEventHandler doesn't fire on inital connections).

**Comment by ColinSullivan1** [comment]
@T-Erpstra - Thank you for raising this issue!

At the time the closed and disconnected event handlers are fired, the connection has been lost, so there is no valid `ConnectedUrl`.  You could always save off the `ConnectedUrl` into a field in your code after connecting, and when the `ReconnectedEventHandler` has been fired, then use that value in your event handlers.

I can certainly see the convenience of a handler when connected... however, we don't offer that functionality at this time.   Since the `Connect` API is blocking, you can wrap it in a method which invokes your own delegate after a successful initial connection, where a `ConnectedUrl` will be valid. 

Do these suggestions sound like they'll work for you?

**Comment by ColinSullivan1** [comment]
I was thinking about this some more, and applications typically view clusters as a single entity - the `ConnectedUrl` is really just for informative purposes.  Would you mind describing your use case?

**Comment by T-Erpstra** [comment]
Thanks for your replies!

Yes, I think those workarounds would solve the "issue".

I just wanted to raise the awareness that they might be nice to have. It's not that these things are blocking me, but this type of information is sometimes useful when trying to detect problems or potential issues (like crappy networks or unstable servers) that doesn't necessarily take the whole system down, but still affects it.
