### ISSUE TITLE
Publish Failure during reconnect

### ISSUE THREAD

**Issue by stephenjannin** [nats-io/nats.net.v1#126]
I’m doing some advanced unit tests.
I have a 3 nodes cluster
I create 2 connections

1 for sending messages on node 1 on subject foo
1 for receiving messages on node 2 on subject foo
I start sending messages every 20 ms
I stop node 1 (the one that is connected to the send thread)

The publish of messages in failing with 2 different types of issues : 
- Socket or IO or NotSupportedException : the underlying stream is not in a good shape. After a while the connection is connected to another node, and I can retry sending the message
- NATSConnectionClosedException : this one is dangerous, because the connection never get reconnected again. I have to create a new one.

Is is the expected behavior ?

**Comment by ColinSullivan1** [comment]
@stephenjannin  - Thank you for raising the issue - I'll look into it.  The publish may throw IO/Socket write related exceptions, but shouldn't get a NATSConnectionClosed exception until all retry attempts have failed.

**Comment by ColinSullivan1** [comment]
@stephenjannin,

I took a closer look at this, and this is expected behavior.  The `NATSConnectionClosedException` should only be thrown if the connection cannot reconnect to any servers in your cluster.  I ran the test below, and did not see that exception thrown, but please let me know if you are seeing anything different.  The .NET client mirrors go, and thus can throw IO/socket exceptions.  That being said, there could be another way for the .NET client to handle publish errors; it warrants further thought.

One pattern you can use is to catch publish exceptions and check that the conn status is not closed.  Then you can block publishing in your application until you are notified reconnection either succeeded through `Options.ReconnectedEventHandler`, or did not with `Options.ClosedEventHandler`

Another choice you have is to continue to retry publishing, which will fail until reconnect logic begins, and then the NATS client will begin to internally buffer your messages to be sent automatically once reconnected.  There may be added complexity in determining which messages have not been sent if the connection cannot ultimately be re-established and you want to know locally which messages won't be delivered.

What are your thoughts?  I'm happy to further discuss.

FYI, Here is a test that succeeded for me:

```
        [Fact]
        public void TestPublishErrorsDuringReconnect()
        {
            utils.StartDefaultServer();

            Task t = new Task(() =>
            {
                Random r = new Random();
                for (int i = 0; i < 500; i++)
                {
                    utils.bounceDefaultServer(r.Next(500));
                }
            }, TaskCreationOptions.LongRunning);
            t.Start();

            byte[] payload = Encoding.UTF8.GetBytes("hello");
            using (var c = new ConnectionFactory().CreateConnection())
            {
                while (t.IsCompleted == false)
                {
                    try
                    {
                        c.Publish("foo", payload);
                    }
                    catch (Exception e)
                    {
                        Assert.IsNotType<NATSConnectionClosedException>(e);
                        Assert.False(c.IsClosed());
                    }
                }
            }   
        }
```

**Comment by ColinSullivan1** [comment]
@stephenjannin, I'm closing this issue, as this is expected behavior.  If you require at least once delivery within NATS, I suggest looking into NATS streaming.
