### ISSUE TITLE
Memory leak on failed connection attempts.

### ISSUE THREAD

**Issue by mawelsh** [nats-io/nats.net.v1#236]
In operation I would like to be able to leave applications running prior to starting the NATS server that expect to see one at some point in their life.  Currently I have a loop:

```
while ((natsConnection == null) || (natsConnection.State != ConnState.CONNECTED))
{
    try
    {
        Log.Information("Creating nats connection with: [{0}]...", opts.Url);

        natsConnection = new ConnectionFactory().CreateConnection(opts);
    }
    catch (Exception e)
    {
        Log.Information(e.ToString());
    }
}
```

natsConnection remains null on failure but the memory usage steadily grows with each attempt.  the memory is not returned on a successful connection.

**Comment by BenDerPan** [comment]
I meet a problem may due to this: when my program running for a long time, the message receive will become duplicated, for example: A send "Hello" once to B , B will receive more than one time, and I step into code, found A call MessageHandler more than one time , even though I A just send once.

but when I reboot both A and B , problem is gone , but will reproduce for a long time running.

**Comment by mawelsh** [comment]
I guess the other question would be is there a more preferred way to startup a service and wait/watch for a NATS server to come online that doesn't memory leak?

**Comment by TheVons** [comment]
We could use this fix too

**Comment by ColinSullivan1** [comment]
I'm looking into this now.
