### ISSUE TITLE
How many IConnections should I open in an app?

### ISSUE THREAD

**Issue by buzzers** [nats-io/nats.net.v1#384]
I am a nats beginner.
I'm writing a game app and using nats as a message bus. We use .NET Core for development.
The program may need to use hundreds of thousands of subjects, and each process may contain tens of thousands of subjects. I wonder if nats will have a significant performance degradation (delay or throughput) in this number of subject scenarios?
If nats can support this scenario, should I use singleton IConnection in each process, or should I open more IConnectionfor for better performance?

**Comment by ColinSullivan1** [comment]
@buzzers,

Thank you for using NATS!  In that case, I'd recommend using many subscribers to a connection.  A single nats connection can handle millions of messages per second.

Compared to subscribers, connections are expensive to establish (especially with TLS), and a single connection can handle thousands of subscriptions.  When doing this, be sure to set [Options.SubscriberDeliveryTaskCount](https://nats-io.github.io/nats.net/class_n_a_t_s_1_1_client_1_1_options.html#a030dfa5eac04072735d7529147d5c562) to something low, starting between 5-10 and scaling upward as necessary.

So I'd start with a single connection and scale upward as necessary, first tuning `SubscriberDeliveryTaskCount` and then # of connections.

**Comment by buzzers** [comment]
Thanks for the reply.
So I plan to use a fixed number of connections (4 to 30) per process, randomly assign the subjects to the connections, and set a lower `SubscriberDeliverTask Count` for each connection.I think this should be a good way.
And if I want to deal with hundreds of thousands to millions of subjects, what should I deploy several nodes of NATS clusters, five or more?

**Comment by ColinSullivan1** [comment]
This really depends on your deployment.  Does every application need to know about all subjects?

A cluster shares interest across servers, so # of subscriptions really doesn't matter there - each server will know of each other server's subscriptions.  Generally you want to scale servers due to # of connections. I'd suggest starting simple and testing and seeing if your hardware/network can keep up with your requirements with a single cluster or even single server.

If that doesn't perform well enough, you can isolate subjects by accounts and using multiple clusters connected via gateways.  Alternatively, use leaf nodes to keep local data local and propagate only what you need to the cluster.  There are a number of options.  I'd suggest starting simple, and expanding as necessary.

https://docs.nats.io/nats-server/configuration/leafnodes
https://docs.nats.io/nats-server/configuration/gateways
https://docs.nats.io/nats-server/configuration/securing_nats/accounts

**Comment by buzzers** [comment]
Yes, our app isn't every process that needs to subscribe to all subjects. The maximum subjects for each process is about 3-5w.
I think I really should start the stress test with the simplest deployment. 
Thank you for your advice.

**Comment by ColinSullivan1** [comment]
Happy to help!  Please let us know how it goes.  Many of the NATS maintainers can be found on [slack](https://slack.nats.io), it's a great place to ask questions from the maintainers and community.
