### ISSUE TITLE
Reuse connection NATS.Client to  NATS server, Web socket

### ISSUE THREAD

**Issue by duyquoc124** [nats-io/nats.net.v1#418]
Hello,
I have a web socket that received message from NATS then send the messages to clients, who connected to my web socket.  I built three servers NATS to load balance
When user connect to my web socket, should I use three connections to NATS ( three connection connect to three servers) or I create new connection for each user (I mean one connection by one username). Currently I have about 10000 users connected to my web socket, there are about 100 subscribers each users.
I read the https://github.com/nats-io/nats.net/issues/350. I know my question may be same this problem but please help me.

**Comment by ColinSullivan1** [comment]
@duyquoc124 , thank you for using NATS!  

You only need one connection to a NATS server cluster.  If that connection is lost, then the client will automatically reconnect to another server in the cluster.  I would start with one NATS connection in your websocket app and see how well that works.  Once connection can get many millions of messages per second (depending on message size).  1M subscribers is a lot, and that'll likely be where your bottleneck will be.  If possible, I'd suggest multiple instances of your websocket application to spread out that subscriber processing in your client.

e.g.
```text
Websocket ---> NATS Client ----------|
                                     |
Websocket ---> NATS Client -----> NATS Server Cluster
                                     |
Websocket ---> NATS Client ----------|
```

Since you have so many subscribers, you'll want to be sure to set [Options.SubscriberDeliveryTaskCount](https://nats-io.github.io/nats.net/class_n_a_t_s_1_1_client_1_1_options.html#a030dfa5eac04072735d7529147d5c562) to something low, starting between 5-10 and scaling upward as you test.

**Comment by duyquoc124** [comment]
Thank you very much @ColinSullivan1
