### ISSUE TITLE
Starting NATS during tests

### ISSUE THREAD

**Issue by lhotrifork** [nats-io/nats.net.v1#426]
Hi,

I want to be able to write integration tests for how my application responds to mesages from NATS.
My plan was to write a custom mock-consumer to respond to messages, spin up NATS during my tests and then wire everything up.

In https://github.com/nats-io/nats.go its easy to run NATS during tests: https://github.com/nats-io/nats.go/issues/467#issuecomment-494610877 
```
import (
	"github.com/nats-io/nats.go"

	natsserver "github.com/nats-io/nats-server/test"
)

const TEST_PORT = 8369

func RunServerOnPort(port int) *server.Server {
	opts := natsserver.DefaultTestOptions
	opts.Port = port
	return RunServerWithOptions(&opts)
}

func RunServerWithOptions(opts *server.Options) *server.Server {
	return natsserver.RunServer(opts)
}

func TestSomething(t *testing.T) {
	s := RunServerOnPort(TEST_PORT)
	defer s.Shutdown()

	sUrl = fmt.Sprintf("nats://127.0.0.1:%d", TEST_PORT)
	nc, err := nats.Connect(sUrl)
	...
	defer nc.Close()
}
```

Does something similar exist for the dotnet library? I've looked at the tests, but it seems that the classes are not public https://github.com/nats-io/nats.net/tree/master/src/Tests

**Comment by ColinSullivan1** [comment]
Thanks for using NATS!

Take a look at:  https://github.com/nats-io/nats.net/blob/master/src/Tests/IntegrationTests/TestSuite.cs
Usage:  https://github.com/nats-io/nats.net/blob/master/src/Tests/IntegrationTests/TestBasic.cs#L75

Our test suite manages the NATS server process, rotates ports so tests can run in parallel, and supports clustering for complex tests.  While the classes aren't public, we don't publish the test framework so that wouldn't help much unless you build locally.  We're certainly OK making those classes public if that'll help you out, and will accept a contribution to that effect.

Otherwise, certainly feel free to copy and modify the TestSuite source to suit your needs.

**Comment by lhotrifork** [comment]
Thank you. I think I will manage without the need for publishing the test framework.

One note for any future readers: this approach requires that a nats-server binary is present on the path when executing the tests. My approach was to download the latest statically linked binary from [releases](https://github.com/nats-io/nats-server/releases) and copying it into the test project by adding this to the `.csproj`
```  
<ItemGroup>
  <None Update="nats-server">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
</ItemGroup>
```
