### ISSUE TITLE
Using unsafe Random for Nkeys.CreateSeed()

### ISSUE THREAD

**Issue by skrysm** [nats-io/nats.net.v1#466]
While searching through the nats.net code base I noticed the method `Nkeys.CreateSeed()` is implemented like this:

```c#
private static string CreateSeed(byte prefixbyte) {
    byte[] rawSeed = new byte[32];

    Random rnd = new Random();
    rnd.NextBytes(rawSeed);

    return Encode(prefixbyte, true, rawSeed);
}
```

Shouldn't this code use `RandomNumberGenerator.GetBytes()` (or something similar) to generate a cryptographic secure seed? The `Random` class is not cryptographically secure (and [its value can even be predicted](https://manski.net/2016/08/breaking-nets-random-class/)).

**Comment by scottf** [comment]
@skrysmanski  We will review, but I don't think this is a problem. The prediction example you use uses the same Random object in order to figure it's prediction. This code uses a new Random object each time, which has a new seed each time. I'd be more interested in it's efficiency. If you like, you are welcome to propose a code change via a PR.

**Comment by sixlettervariables** [comment]
I'll handle this in my current NKeys PR. Thanks for pointing that out @skrysmanski.

**Comment by sixlettervariables** [comment]
Thank you again for bringing this up @skrysmanski! Fix will be in the next release.
