### ISSUE TITLE
Default event handlers log to stderr.

### ISSUE THREAD

**Issue by khabalevskyi** [nats-io/nats.net.v1#535]
## Defect
NATS.Client default event handlers log to stderr when you disconnect from NATS server. It will log the disconnected and closed events to stderr even when you explicitly ask to be disconnected by calling the Dispose method.

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `NATS.Client` and `nats-server`:
NATS.client version: 0.14.3
nats-server verstion: 2.2.1

#### OS/Container environment:
Windows 10 Enterprise
OS Build 19042.1415

#### Steps or code to reproduce the issue:
This console creates connection with default options and then disposes it. Log to stderr is decorated to be Red and prefixed with [Error].  

```c#
using System;
using System.IO;
using System.Text;
using NATS.Client;

namespace ConnectionEventsLog
{
    class Program
    {
        static void Main(string[] args)
        {
            ConsoleErrorWriterDecorator.SetToConsole();
            Options options = ConnectionFactory.GetDefaultOptions();

            //options.DisconnectedEventHandler = (sender, eventArgs) => { };
            //options.ClosedEventHandler = (sender, eventArgs) => { };

            using (IConnection connection = new ConnectionFactory().CreateConnection(options))
            {
                Console.WriteLine($"Connection state is {connection.State}");
            }

            Console.WriteLine("Connection disposed");

            Console.ReadKey();
        }
    }

    public class ConsoleErrorWriterDecorator : TextWriter
    {
        private readonly TextWriter _originalConsoleStream;

        public ConsoleErrorWriterDecorator(TextWriter consoleTextWriter)
        {
            _originalConsoleStream = consoleTextWriter;
        }

        public override void WriteLine(string value)
        {
            ConsoleColor originalColor = Console.ForegroundColor;
            Console.ForegroundColor = ConsoleColor.Red;

            _originalConsoleStream.WriteLine($"[Error] {value}");

            Console.ForegroundColor = originalColor;
        }

        public override Encoding Encoding => Encoding.Default;

        public static void SetToConsole()
        {
            Console.SetError(new ConsoleErrorWriterDecorator(Console.Error));
        }
    }
}
```
Output:
![Actual](https://user-images.githubusercontent.com/11831485/148225238-411212f8-4d4b-463a-ae57-793c6bc466f1.PNG)

#### Expected result:
Default event handlers log events to stdout and errors to stderr

#### Actual result:
Default event handlers log events to stderr and errors to stderr

#### Some hints:
Here are the places in NATS.cs
WriteEvent methods both call Console.Error.WriteLine(...)
https://github.com/nats-io/nats.net/blob/master/src/NATS.Client/NATS.cs#L216
https://github.com/nats-io/nats.net/blob/master/src/NATS.Client/NATS.cs#L221

**Comment by scottf** [comment]
@khabalevskyi @LaurensVergote I will run this by a few other people to discuss it with them, but I doubt this will be done.
The whole point of building a default handler was to just have something. We wanted to ensure that there was some output somewhere because those events used to be discarded.
We also believe that writing to the console or stderr is actually not a best practice and these are NOT intended for production, it is intended that the user implement something that make sense in their application.

**Comment by LaurensVergote** [comment]
@scottf I do agree that ideally the user implements something to handle this instead of the default handlers that are currently implemented, but I believe logging every event to stderr by default a bit counter productive. Minimal code samples/examples will now produce a load of errors, which aren't actualy errors. Additionally, if in the future additional handlers are added, updating your client version will result in new errors being logged while previously there were none. But this is more of a design thing than a real issue.
Providing a default is good, but I'd have everything log to stdout instead of stderr (or the mix that I've submitted as pull request).

_In the product I'm working on, I've now implemented event handlers for all the events seperately which boils down to what's been implemented in #546  so my product is not impacted anymore. We noticed these errors when upgrading from 0.12 to 0.14.4 in our software to start using JetStream._

**Comment by ColinSullivan1** [comment]
@LaurensVergote , the general idea behind the default handlers are for users to more quickly identify conditions in their application that may be unexpected or to log a significant state change in NATS. When there are connectivity issues the first recommendation maintainers will make will be to implement these handlers - so often so that we made these defaults.

stderr was chosen to maintain parity with the golang client, although there's argument for non-errors to be written to stdout as you have done in the pull request.  These statements to stderr can surface up as errors in CI/CD, so I'm amenable to writing to stdout except for disconnected/closed events with an error, and the async error handler.

**Comment by scottf** [comment]
Fixed in https://github.com/nats-io/nats.net/pull/560
