### ISSUE TITLE
Add GetMessage/DeleteMessage on IJetStream

### ISSUE THREAD

**Issue by thinkbeforecoding** [nats-io/nats.net.v1#540]
## Feature Request
Add GetMessage/DeleteMessage on IJetStream

#### Use Case:
Get/Delete are currently implemented on IJetStreamManagement and return a MsgInfo. It makes sense, in a tooling perspective.
But in some scenario, Get/Delete message can be required in services (Custom sharding), and having to use both IJetStream and IJetStreamManagement muddies the code. 

#### Proposed Change:
Declare GetMessage and DeleteMessage on the IJetStream interface and implement them in the JetStream class. GetMessage would return a Msg instead of a MsgInfo.
There would also be a GetMessageAsync / DeleteMessageAsync like done in #539 .

#### Who Benefits From The Change(s)?
Accessing individual messages from the seq id is used in conjunction with subscriptions in HeadersOnly mode. The subscriber is notified of messages without the body, but can decide to access the body of some selected messages.

#### Alternative Approaches
Use the IJetStreamManagement methods.

**Comment by scottf** [comment]
This change will have to be discussed by the client parity team. 
The problem with adding this to the api is that we have to consider it in all clients, not that all clients have to be exactly equal but we do try to maintain some amount of parity. And since you can wrap the call yourself and the management context is actually very light, I don't see the problem with using both the management api and the regular api. We are really just separating concerns by having different interfaces.

**Comment by aricart** [comment]
Streams are supposed to be log data, consumers process them and messages remain unless the stream's storage policy discards them.  The management APIs can obviously do that sort of operation as they are intended as management.

Operations like sharding etc can be easily implemented by having a work queue that then re-publishes a message to a different stream - this provides you what you are looking for. Processing a message successfully discards the message. Your consumer can then re-publish the message under a different subject targeting a different stream, and after waiting for the successful acknowledgment from the server that the message was stored, ack the message which in turn deletes it from the original stream.

This more closely aligns with processing of message, rather than management of the stream, and can be done today without adding API

**Comment by thinkbeforecoding** [comment]
I closed the PR for now to avoid confusion.
