### ISSUE TITLE
Travis CI for the .NET client

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#62]
It would be nice to have continuous integration for the .NET client.  Currently, Travis CI supports mono and a few test frameworks as beta.  The .NATS C# test suite uses the Visual Studio Test Suite to avoid external dependencies.

Investigate:
- Level of support (now and future) in Travis CI
- Other user experiences of .NET in Travis CI
- NUnit vs xunit, including level of effort to convert

**Comment by cstlaurent** [comment]
Hi,

I don't know what is the progress on this one, but I think I could help with some pull requests if you are ok with it.

Here are my recommendations:
- **Test Framework**: I may be biased here since it's my framework of choice, but I think considering the fact that the CoreFx and ASP.NET teams chose XUnit as their official test framework it may provide more support in the future, switching from VS Tests to Xunit would be a good idea.
- **CI server**: I think Travis CI is not enough for a C# project since it only offers Mono on Linux support for now, and I'm pretty sure this is not the main deployment configuration for users. I think using AppVeyor would be a better idea for now since it offers CI builds on Windows machine with full .NET framework. Travis CI or maybe Circle CI could be used to test on Mono and .NET Core on Linux eventually.

Let me know what you think!

**Comment by ColinSullivan1** [comment]
@cstlaurent Thank you for the recommendations!  I was planning on moving to xunit for exactly the reasons you mentioned, and in fact the new NATS streaming C# library (under development) will use xunit.  Any PRs you'd like to submit to move over to xunit would be greatly appreciated!

I agree with your note on the CI server, and will certainly look into AppVeyor.  However, since everything we use is already on Travis CI, I'd like to see how well it works first.

**Comment by cstlaurent** [comment]
I think this issue could be closed after PR #87 and #89
