### ISSUE TITLE
Question:  How do I subscribe and receive messages that are already on the server?

### ISSUE THREAD

**Issue by fkazemzadeh** [nats-io/nats.net.v1#76]
Hi, it seems like the subscriber example will only receive messages while the example publisher is publishing (both sessions going).  Is this the case?  How do I subscribe and receive messages after they have already been published?

**Comment by ColinSullivan1** [comment]
@fkazemzadeh, Thank you for your interest in NATS!  What you are seeing is expected behavior.  Subscribing applications can only receive messages that are published when they are actively subscribed.  NATS philosophy holds that high levels of quality-of-service should be built into the client. Only request-reply is built in. 

Core NATS does not provide:
- Persistence
- Transactions
- Enhanced delivery modes
- Enterprise queueing

That being said, there will soon be a beta release of a streaming product built on top of NATS which will support persistence and enhanced delivery modes - which is exactly what you are describing in your question.

I invite you to join our slack community!  Information can be found here:  http://nats.io/community/
