### ISSUE TITLE
.NET Core Client

### ISSUE THREAD

**Issue by oaiey** [nats-io/nats.net.v1#80]
I wanted to evaluate NATS for a  .NET Core project. Unfortunately, the NuGet is only for net45. Is it possible to have the next version also include a build for .NET Core?

**Comment by ColinSullivan1** [comment]
Thank you for bringing this up!  A .NET core release is on our list.  Previous versions of .NET core did not support some features we needed around TLS, but we'll re-evaluate and I'll update this issue.  Thanks!

**Comment by lor3** [comment]
I've done a quick and dirty conversion: https://github.com/lor3/csnats.  Hopefully it can be of use to someone else.

All tests are passing though I removed EncodedCon because ISerializable is not available in .NET core so it'll require some refactoring (or wait until they bring it back).
Converted tests to use Xunit as it is the most mature testing library on core.

I renamed the source folder simply because `dotnet pack` uses it to name the nuget package.

**Comment by ColinSullivan1** [comment]
Good job!  Your contribution is highly appreciated!  Perhaps with some conditional compilation your work can be merged in...   I've been meaning to move to xunit as well - thanks!

**Comment by megakid** [comment]
Loving the look of this.  Thanks @lor3

**Comment by ColinSullivan1** [comment]
After the C# streaming client is wrapped up (currently underway), .NET core won't be far behind.  Again, great to see contributions like this!
